version: '3'

services:
  bayeta:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
